---
title: "data_challenge"
author: "Zongyan Wang"
date: "March 25, 2016"
output: pdf_document
---
# Read data and packages
```{r}
# Upload packages for data clean and analysis
require(plyr)  #data clean
require(dplyr) #data clean
require(tidyr) #data clean
require(ggplot2)  # visualzation
require(XML)   # web scriping
require(testthat) #test model
require(kernlab) # kernel and SVM
require(reshape2) 
require(caret) # Cross - Validation k fold
require(maps) # heatmap: map_data
require(ggmap) # for heatmap
```
# Read file
```{r}
# Read Data and function files
LC <- read.csv(file.choose(), header = T) #Please read LC_biz_all.csv
source("clean_f2.R") # functions for cleaning the data
source("plot_f2.R") # functions for plot(heatmap)
source("analysis_f2.R") # functions for plot and data analysis
```

# Data clean
```{r}
lc <- perToN(LC)  # transfer percentage to numeric
lc <- replaceBlank_all(lc) # replace the blank
lc <- dateToNum(lc) # transform earliest_cr_line from date to numeric
lc <- lc %>% select(-id,  -emp_title,
                    -last_pymnt_d, -next_pymnt_d,
                    -zip_code,-issue_d, -last_credit_pull_d)
```
# Data Summary
```{r}
n.factor_all(lc)
hasNA_all(lc)
```
## ANOVA
```{r}
lc1 <- lc[, !(colnames(lc) %in% c(names(n.factor_all(lc))))]
lc1$loan_status <- lc$loan_status
lc1 <- lc1 %>% subset(!loan_status == "Current")
anova.p <- data.frame(var = names(anova(lc1)), p.value = anova(lc1)) 
anova.p_plot <- anova.p %>% subset(p.value < 0.05) %>%
  mutate(var = reorder(x = var, X = p.value, min)) %>%
  ggplot(aes(x = var, y = p.value, color = var)) +
  geom_point() +
  geom_hline(yintercept = 0.01, colour = "red", linetype = 3) +
      labs(x = "Variable", y = "p-value", title = "ANOVA p-value")
anova.p_plot
sig.names <- as.character((anova.p %>% subset(p.value < 0.01))$var)
var.names <- c(sig.names, names(n.factor_all(lc)))
```
## subset the data
```{r}
lc2 <- lc[,c(var.names)] 
lc2 <- lc2 %>% select(-purpose)
lc.categorical <- lc2[,names(n.factor_all(lc2))]
lc.categorical <- lc.categorical %>% select(-loan_status)
lc.numeric <- lc2[,!names(lc2) %in% names(n.factor_all(lc2))]
# Transform the categorical column to multiple numeric columns
categorical.list <- apply(lc.categorical, 2, function(x) model.matrix(~ x + 0))
lc3 <- as.data.frame(cbind(categorical.list, lc.numeric))
lc3$loan_status <- lc$loan_status
# Group the loan_status into 3 groups
lc3 <- lc3 %>% mutate(y = !(loan_status == "Current"))
lc3$y[lc3$loan_status == "Fully_Paid"] <- 2
lc3 <- lc3 %>% select(-loan_status)
```
## Logistic Regression
```{r}
lc4 <- lc3 %>% subset(y != 0)
lc4$y[lc4$y == 2] <- 0 # Fully Paid set to be zero, while potential delinquency events set to be 1
log.f <- logistic(lc4)
pred <- predict(log.f, lc4, type = "response")
pred1 <- as.numeric(pred >= 0.5)
# in-sample prediction accuracy
1 - sum(pred1 == lc4$y, na.rm = T)/length(pred1)
# out-of-sample prediction accracy
cv_error <- cv_k(lc4)
cv_error
#Plot the significant value
significant_plot <- coeff_plot1(log.f, sig = T, 0.1)
print(significant_plot)
#Plot the coefficient value
coefficient_plot <- coeff_plot1(log.f, sig = F, 0.1)
print(coefficient_plot)
# What is the prediction for Status "Current"?
current <- lc3 %>% subset(y == 0)
pred.current <- predict(log.f, current, type = "response")
```
## Kernel SVM
```{r}
# Prepare for kernel SVM
lc4 <- lc4[-which(is.na(lc4$percent_bc_gt_75) | is.na(lc4$revol_util) | is.na(lc4$bc_util)),]

l.kern <- svm(lc4, "vanilladot")
l.kern
# New data
newdata <- as.matrix(lc4%>% select(-y))
pred.kern <- predict(l.kern, newdata)
# in-sample prediction accuracy
1 - sum(pred.kern == lc4$y, na.rm = T)/length(lc4$y)
# cross validation error
cv.kernel.error <- cv_ksvm(lc4, "vanilladot", k = 10)
cv.kernel.error
```