---
title: "fitToAll"
author: "Zongyan Wang"
date: "March 28, 2016"
output: pdf_document
---
# Read data and packages
```{r}
# Upload packages for data clean and analysis
require(plyr)  #data clean
require(dplyr) #data clean
require(tidyr) #data clean
require(reshape2) # data clean
require(ggplot2)  # visualzation
require(XML)   # web scriping
require(testthat) #test model
require(kernlab) # kernel and SVM
require(datasets) # State data
require(caret) # Cross - Validation k fold
require(RCurl) # load the website link
require(maps) # heatmap: map_data
require(ggmap) # for heatmap
require(gridExtra)

```
# Read file
```{r}
# Read Data and function files
LC <- read.csv(file.choose(), header = T) #Please read LC_biz_all.csv
source("clean_f2.R") # functions for cleaning the data
source("plot_f2.R") # functions for plot(heatmap)
source("analysis_f2.R") # functions for plot and data analysis
```

# Data clean
```{r}
lc <- perToN(LC)  # transfer percentage to numeric
lc <- replaceBlank_all(lc) # replace the blank
# Transform earliest_cr_line, issue_d, last_pymnt_d from str to numeric
lc <- lc %>% dateToNum(., "earliest_cr_line") %>%
  dateToNum(., "issue_d") %>% dateToNum(., "last_pymnt_d")  

lc <- lc %>% select(-id,  -emp_title,-zip_code)
```
# Data Summary
```{r}
n.factor_all(lc)
hasNA_all(lc)
```
## ANOVA
```{r}
lc1 <- lc[, !(colnames(lc) %in% c(names(n.factor_all(lc))))]
lc1$loan_status <- lc$loan_status
lc1 <- lc1 %>% subset(!loan_status == "Current")
anova.p <- data.frame(var = names(anova(lc1)), p.value = anova(lc1)) 
anova.p_plot <- anova.p %>% subset(p.value < 0.05) %>%
  mutate(var = reorder(x = var, X = p.value, min)) %>%
  ggplot(aes(x = var, y = p.value, color = var)) +
  geom_point() +
  geom_hline(yintercept = 0.01, colour = "red", linetype = 3) +
      labs(x = "Variable", y = "p-value", title = "ANOVA p-value")
anova.p_plot
ggsave(filename = "anova.p_plot1.png", plot = anova.p_plot, path = ".",  
       width = 10, height = 6, dpi = 400)
sig.names <- as.character((anova.p %>% subset(p.value < 0.01))$var)
var.names <- c(sig.names, names(n.factor_all(lc)))
```
## subset the data
```{r}
lc2 <- lc[,c(var.names)] 
lc2 <- lc2 %>% select(-purpose)
lc.categorical <- lc2[,names(n.factor_all(lc2))]
lc.categorical <- lc.categorical %>% select(-loan_status)
lc.numeric <- lc2[,!names(lc2) %in% names(n.factor_all(lc2))]
# Transform the categorical column to multiple numeric columns
categorical.list <- apply(lc.categorical, 2, function(x) model.matrix(~ x + 0))

```
# Interested in the classification between Fully Paid and Potential Delinquency Events
```{r}
lc3 <- as.data.frame(cbind(categorical.list, lc.numeric))
lc3$loan_status <- lc$loan_status
# Group the loan_status into 3 groups
lc3 <- lc3 %>% mutate(y = !(loan_status == "Current"))
lc3$y[lc3$loan_status == "Fully_Paid"] <- 2
lc3 <- lc3 %>% select(-loan_status)

## Logistic Regression
lc4 <- lc3 %>% subset(y != 0)
lc4$y[lc4$y == 2] <- 0 # Fully Paid set to be zero, while potential delinquency events set to be 1
log.f <- logistic(lc4)
pred <- predict(log.f, lc4, type = "response")
# Compare the pred and true value
compare.data <- data.frame(pred = pred, true = lc4$y)

# in-sample prediction accuracy
# prediction accuracy when threshold = 0.5
pred1 = as.numeric(pred > 0.25)
1 - sum(pred1 == lc4$y, na.rm = T)/length(pred1)
coeff.plot <- coeff_plot1(log.f, sig = F,sig.value = 0.05)
ggsave(filename = "FD_coeff_plot1.png", plot = coeff.plot, path = ".",  
       width = 10, height = 6, dpi = 400)
# Prediction and true status when threshold = 0.5 plot
pred_type_plot <- plot_pred_type_distribution(compare.data, 0.5)
print(pred_type_plot)
ggsave(filename = "FD_pred_type_plot1.png", plot = pred_type_plot, path = ".",  
       width = 15, height = 6, dpi = 400)

# roc, cost of FP = 1, cost of FN = 5 
# Calculate the roc(FP: pred=1,true=0; FN:pred=0, true=1)
roc <- calculate_roc(compare.data, 1, 5, n = 100)
# Plot the roc, cost of FP = 1, cost of FN = 5 
plot.roc <- plot_roc(roc, 0.5, 1, 5)
print(plot.roc)
ggsave(filename = "FD_plot_roc1.png", plot = plot.roc, path = ".",  
       width = 10, height = 6, dpi = 400)

# out-of-sample prediction accracy
cv_error <- cv_k(lc4)
cv_error
#Plot the significant value
significant_plot <- coeff_plot1(log.f, sig = T, 0.1)
print(significant_plot)
#Plot the coefficient value
coefficient_plot <- coeff_plot1(log.f, sig = F, 0.1)
print(coefficient_plot)
```
# Interested in the classification between Current and Potential Delinquency Events
```{r}
lc3 <- as.data.frame(cbind(categorical.list, lc.numeric))
lc3$loan_status <- lc$loan_status
# Group the loan_status into 3 groups
lc3 <- lc3 %>% mutate(y = !(loan_status == "Fully_Paid"))
lc3$y[lc3$loan_status == "Current"] <- 2
lc3 <- lc3 %>% select(-loan_status)

## Logistic Regression
lc4 <- lc3 %>% subset(y != 0)
lc4$y[lc4$y == 2] <- 0 # Fully Paid set to be zero, while potential delinquency events set to be 1
log.f <- logistic(lc4)
pred <- predict(log.f, lc4, type = "response")
# Compare the pred and true value
compare.data <- data.frame(pred = pred, true = lc4$y)

# in-sample prediction accuracy
# prediction accuracy when threshold = 0.5
pred1 = as.numeric(pred > 0.5)
1 - sum(pred1 == lc4$y, na.rm = T)/length(pred1)
coeff.plot <- coeff_plot1(log.f, sig = F,sig.value = 0.05)
ggsave(filename = "CD_coeff_plot1.png", plot = coeff.plot, path = ".",  
       width = 15, height = 6, dpi = 400)
# Prediction and true status when threshold = 0.5 plot
pred_type_plot <- plot_pred_type_distribution(compare.data, 0.14)
print(pred_type_plot)
ggsave(filename = "CD_pred_type_plot1.png", plot = pred_type_plot, path = ".",  
       width = 10, height = 6, dpi = 400)
# roc, cost of FP = 1, cost of FN = 5 
# Calculate the roc(FP: pred=1,true=0; FN:pred=0, true=1)
roc <- calculate_roc(compare.data, 1, 5, n = 100)
# Plot the roc, cost of FP = 1, cost of FN = 5 
plot.roc <- plot_roc(roc, 0.5, 1, 5)
print(plot.roc)
ggsave(filename = "CD_plot_roc1.png", plot = plot.roc, path = ".",  
       width = 10, height = 6, dpi = 400)

# out-of-sample prediction accracy
cv_error <- cv_k(lc4, threshold = 0.14)
cv_error
#Plot the significant value
significant_plot <- coeff_plot1(log.f, sig = T, 0.1)
print(significant_plot)
#Plot the coefficient value
coefficient_plot <- coeff_plot1(log.f, sig = F, 0.1)
print(coefficient_plot)

```